[project]
name = "protect-shield"
authors = ["Core Dev Team"]
description = "A secure, blockchain-native asset protection and generation platform"
telemetry = false
requirements = []
[contracts.shield-nft]
path = "contracts/shield-nft.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
